select COUNT(IDMEDICO) from MEDICOS
WHERE SEXO = 'F' AND COSTO_CONSULTA > 1000

select COUNT(m.IDMEDICO) FROM MEDICOS m
INNER JOIN ESPECIALIDADES e on m.IDESPECIALIDAD= e.IDESPECIALIDAD
WHERE e.NOMBRE like 'Gastroenterologia' or e.NOMBRE like 'Pediatría'

SELECT COUNT(distinct IDPACIENTE) from TURNOS
WHERE DURACION > (select AVG(DURACION) from TURNOS)

select COUNT(p.IDPACIENTE) as CanntidadTurnos , p.nombre+' '+ p.apellido as NombreApellido from PACIENTES p 
INNER join TURNOS t on p.IDPACIENTE = t.IDPACIENTE
GROUP BY p.IDPACIENTE, p.nombre+' '+ p.apellido
ORDER BY CanntidadTurnos desc

select AVG(m.COSTO_CONSULTA) as PromedioCosto from MEDICOS m
INNER JOIN ESPECIALIDADES e on m.IDESPECIALIDAD = e.IDESPECIALIDAD
WHERE e.NOMBRE like 'Oftalmología'

select  m.COSTO_CONSULTA * (1-o.COBERTURA) from MEDICOS m 
INNER JOIN TURNOS t on t.IDMEDICO = m.IDMEDICO
inner JOIN PACIENTES p on p.IDPACIENTE = t.IDPACIENTE
INNER JOIN OBRAS_SOCIALES o on o.IDOBRASOCIAL = p.IDOBRASOCIAL
WHERE t.IDTURNO = 146

select COUNT(t.IDTURNO) from TURNOS t 
INNER JOIN MEDICOS m on  m.IDMEDICO = t.IDMEDICO
WHERE m.NOMBRE LIKE 'Flavia' and m.APELLIDO LIKE 'Rice'

SELECT m.apellido, m.FECHAINGRESO from MEDICOS m 
WHERE SEXO like 'M'
ORDER BY m.FECHAINGRESO ASC

select o.nombre from OBRAS_SOCIALES o 
INNER JOIN PACIENTES p on o.IDOBRASOCIAL = p.IDOBRASOCIAL
INNER JOIN TURNOS t on p.IDPACIENTE = t.IDPACIENTE
INNER JOIN MEDICOS m on m.IDMEDICO = t.IDMEDICO
INNER JOIN ESPECIALIDADES e on e.IDESPECIALIDAD = m.IDESPECIALIDAD
WHERE e.NOMBRE LIKE 'Odontología'

SELECT COUNT(distinct p.IDPACIENTE)  FROM PACIENTES p 
INNER join TURNOS t on p.IDPACIENTE = t.IDPACIENTE
WHERE YEAR(t.FECHAHORA) <> 2019
